### ISSUE TITLE
DFD Comments - Sept 19

### ISSUE THREAD

**Issue by germonprez** [alreshaidan/assignment1_3420#5]
A few comments: 

1) You have to be consistent in your naming: 

Are Licenses and OSS Results the same thing to you? if they are, they should be named the same thing. 

Same with Package & License Info Request. Is this the same as Request for Package & License Info? If they are the same, they have to have the same names. 

2) Are OSS Results the same as Package & License Info Response. 

Overall, the structure is good but you have to really get your naming to be consistent. 

Matt

**Comment by alreshaidan** [comment]
Dear Dr. Germonprez

I wonder if I did right in the DFD .
please  let me know if I miss something.

Thank you,

Bader,

**Comment by germonprez** [comment]
Nearly done. 

This area needs to be fixed. 

<img width="505" alt="screen shot 2016-09-23 at 5 32 24 am" src="https://cloud.githubusercontent.com/assets/656208/18783039/3059d56a-814f-11e6-8d5e-319b3ad1206c.png">

Simply in the sense that you need to rename OSS Results here so that it is consistent with the dataflow label that is returning to the manager

**Comment by alreshaidan** [comment]
Good evening Professor Germonprez,

I fixed the naming for DFD.

Thank you,

Bader
